spring:
  application:
    name: scheduler-service

---
spring:
  profiles: development

quartz2:
  app-default-scheduler: quartz2://appGroup/sampleTimer?cron=0+0/%s+1-23+?+*+MON-SUN

thread-pooling:
  core-pool-size: 25
  max-pool-size: 300

rest-template:
  max-connections: 100
  max-connections-per-route: 100
  http-client:
    connection-timeout: 0
    socket-timeout: 0
    connection-request-timeout: 0

server:
  tomcat:
    accept-count: 100
    max-connections: 10000
    max-threads: 200

